### ISSUE TITLE
Expose Access Token in Lens SDK for server-side verification of user

### ISSUE THREAD

**Issue by wingedrhino** [lens-protocol/lens-sdk#252]
**Is your feature request related to a problem? Please describe.**

The lens SDK does not expose the access token directly. However, the
[verify-jwt](https://docs.lens.xyz/docs/verify-jwt) endpoint requires it.
This seems to be the only way for a lens protocol implementer's API
server to verify that the user has logged in through lens.

**Describe the solution you'd like**

Add a `getAccessToken(): Promise<string>` method to `IAuthentication`.

Re-use the code currently in `Authentication.getRequestHeader` and pull it
out into a publicly exposed method on `IAuthentication`.

**Describe alternatives you've considered**

Adding `getRequestHeader` to the public interface. But this seems a little too
use-case specific. You don't always need the access token for adding to your
request headers.

**Additional context**

Current workaround from a package that uses the official SDK:

```typescript
async function getCredentials (lens: LensClient): Promise<string> {
const lensAuth = lens.authentication as Authentication
const getHeadersResp = await lensAuth.getRequestHeader()
if (getHeadersResp.isFailure()) {
  return ''
}
const headers = getHeadersResp.unwrap()
const authHeaderValue = headers.authorization
if (authHeaderValue.length < 7) {
  return ''
}
const accessToken = authHeaderValue.slice(7)
return accessToken
}
```

**Comment by krzysu** [comment]
would a simple implementation like this be enough or do we also need to include "the refresh" flow?

```
async getAccessToken(): Promise<string | undefined> {
  const credentials = await this.storage.get();

  return credentials?.accessToken;
}
```

**Comment by wingedrhino** [comment]
> would a simple implementation like this be enough or do we also need to include "the refresh" flow?

By "the refresh flow", do you mean the ability to automatically check if the token is expired and then fetch a fresh one from the server? Yep, in a high level SDK that is VERY useful.

I cannot think of many usage scenarios where I would want an old, expired lens access token :smile:

**Comment by cesarenaldi** [comment]
@wingedrhino this seems a pretty good first issue. Would you like to submit a PR?

**Comment by wingedrhino** [comment]
@cesarenaldi I can take this up over the weekend!

**Comment by ashutosh887** [comment]
Let me work on this now @cesarenaldi Sir

**Comment by wingedrhino** [comment]
I got a little caught up. Wasn't in the best of health.

@ashutosh887 feel free to take it up if you're more free! There's also a little bug somewhere in the CredentialStorage class that causes isAuthenticated() to return false if you reload the page.

**Comment by cesarenaldi** [comment]
This will go out in 1.1.0 stable release.
