### ISSUE TITLE
Switch from HS256 to ES256 for signing JWT tokens

### ISSUE THREAD

**Issue by wingedrhino** [lens-protocol/lens-sdk#253]
**Is your feature request related to a problem? Please describe.**

Right now, if a lens protocol implementer had to verify a lens token as belonging to a user,
the only way to do that is to use the [verify-jwt](https://docs.lens.xyz/docs/verify-jwt) method.

This ALWAYS requires an extra network hop in the backend, slowing down lens apps.

**Describe the solution you'd like**

1. We switch from HS256 to  ES256 in the lens backend, for JWT signing
2. The public keys are rotated by the lens backend, and exposed via JWKS at an endpoint like
     `https://api.lens.dev/well-known/jwks.json`.
3. The lens implementer's backend (or even frontend) uses a JWKS-friendly library that caches
    the public keys. See https://github.com/auth0/node-jwks-rsa/blob/master/EXAMPLES.md#caching
    for an example.

**Describe alternatives you've considered**

RS256 is probably much better known; but at this point there's a LOT of library support for ES256.

**Additional context**

ES256 uses the secp256r1 curve.

**Comment by desfero** [comment]
@wingedrhino thanks for the interesting proposal. 
@joshstevens19 any thoughts on this to implement on the backend side?

**Comment by joshstevens19** [comment]
Thanks for sharing this, we revisiting JWT authentication in lens v2 and we going to be changing a few things to make it less portable (from device to device), we also will investigate what you said above when we do this. The LENS SDK code doesn’t touch these parts so closing here for now but will update this ticket with details once the new JWT authentication is in lens v2. 

We can not change this directly now without hurting all application and with lens v2 close we will make these breaking changes then. 

Thanks for raising this is a great idea.
