### ISSUE TITLE
useActiveProfile always returns null

### ISSUE THREAD

**Issue by lsbyerley** [lens-protocol/lens-sdk#281]
**Describe the bug**
While following the NextJS example, the `useActiveProfile` hook always seems to return null even when signed in with a wallet that has a lens profile.

**To Reproduce**
Following this example from the docs, profile is always null https://github.com/lens-protocol/lens-sdk/blob/11aa5034e1ff2ee3bd24a86d02deebba76573489/examples/nextjs/components/auth/WhenLoggedInWithProfile.tsx#L30

**Expected behaviuor**
I have a lens protocol profile and after signing in, I would expect profile to not be null.

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App
- [ ] React Native 

**Version of the packages you are using**
```
"next": "13.2.3",
"@lens-protocol/react-web": "0.6.0",
"@lens-protocol/wagmi": "0.6.0",
"ethers": "5.7.2",
"wagmi": "0.12.8"
```

**Additional context**
Is there any other special steps I am missing? I'm not sure why the profile would be null

**Comment by cesarenaldi** [comment]
Hi @lsbyerley,

Are you using `staging` or `production` environment configuration?

Is this a test profile (ending in `.test`) or a mainnet one (ending in `.lens`)?

**Comment by lsbyerley** [comment]
Hello @cesarenaldi,

I am using `staging` for the `environment` param. The profile is a mainnet one with a `.lens` ending. So, maybe that is why?

**Comment by cesarenaldi** [comment]
@lsbyerley that is correct. You are pointing the SDK to staging env (mumbai, Lens API for mumbai, etc.) but the profile you are referring to is on Polygon mainnet.

You have several options to create a testnet profile:
- using the `useCreateProfile` hook,
- OR via the `examples/web-wagmi` app within the Lens SDK monorepo (you will need to check out the code and build it as per instructions),
- OR using https://testnet.lenster.xyz/new/profile

**Comment by cesarenaldi** [comment]
If you don't have any objection I am going to close this ticket. Let me know if you think it's still relevant and we can reopen it.
