### ISSUE TITLE
Could we include Global Protocol Stats hooks

### ISSUE THREAD

**Issue by cesarenaldi** [lens-protocol/lens-sdk#283]
Could we include [Global Protocol Stats](https://docs.lens.xyz/docs/global-protocol-stats) as a hook? This would be beneficial for numerous statistics applications to access Lens protocol statistics.

_Originally posted by @daoleno in https://github.com/lens-protocol/lens-sdk/discussions/48#discussioncomment-5276927_

**Comment by ashutosh887** [comment]
Let me work on this @cesarenaldi

**Comment by cesarenaldi** [comment]
@ashutosh887 sorry, I didn't reply to you directly. The Lens SDK is open-source, feel free to submit a PR anytime.

**Comment by cesarenaldi** [comment]
Parking this for now. As our Lens BigQuery expands in quantity and quality of the data we think BigQuery should be more suitable to power any stats based app/experience. Over time some of the stats related queries available in Lens API will be removed.
