### ISSUE TITLE
Feature: Support conditional triggering of queries

### ISSUE THREAD

**Issue by daoleno** [lens-protocol/lens-sdk#312]
Similar to the [enable](https://tanstack.com/query/v4/docs/react/guides/disabling-queries) option in ﻿useQuery of React Query, I would like to trigger a query only when certain conditions are met.

**Comment by cesarenaldi** [comment]
hi @daoleno, I totally understand the feature requested, I remember entertaining this idea with someone. Very similar to Apollo useQuery `skip`.

I believe in that occasion the dev decided to opt for conditionally render a child component. Did you entertain this idea? Any other alternative you might have considered?

For the next time, can I please ask you to use the provided template if possible?

```
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
```

**Comment by meta113** [comment]
Posting requires gas fee! Interaction, likes and comments are also needed.

**Comment by cesarenaldi** [comment]
> Posting requires gas fee! Interaction, likes and comments are also needed.

@meta113 you lost me there, can you please clarify how you see it relates with the conversation?

In general, posting on lens is for the vast majority subsidized by the Protocol. So gas is not needed for the vast majority of users. Comments and reactions (likes) are also features of the Protocol, subsidized as well.

**Comment by cesarenaldi** [comment]
Work in progress on this available here: https://github.com/lens-protocol/lens-sdk/pull/467

**Comment by cesarenaldi** [comment]
This will be implemented in the shape of "lazy hooks". Closing this issue for now.
