### ISSUE TITLE
Issue with the package!!

### ISSUE THREAD

**Issue by swarajbachu** [lens-protocol/lens-sdk#334]
**Describe the bug**

![WhatsApp Image 2023-05-14 at 9 20 00 PM](https://github.com/lens-protocol/lens-sdk/assets/97094800/57f979b7-6830-4441-b9bc-6353e4c10cc2)

**To Reproduce**
Just installing the basic @lens-protocol/wagmi and creating the wrapper gives this error, next js 13.4, page directory, wrap wagmi in _app.tsx

**Expected behaviuor**
Error with the module 

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App
- [ ] React Native 

I have the fix, I found the fix, but unable to the find the exact file, the problem is in /wagmi/dist/lens-protocol-wagmi.cjs.js file, so, if someone can help me, i can help with the fix

**Comment by desfero** [comment]
Hello @swarajbachu, thanks for reporting an issue.
Could you try to add '@lens-protocol' to the `transpilePackages` in the nextjs configuration (like we did in our next.js exampel over here: https://github.com/lens-protocol/lens-sdk/blob/main/examples/nextjs/next.config.js#L6) to see if that would help?

**Comment by swarajbachu** [comment]
done cool, cool its working thank you
