### ISSUE TITLE
In version 1.01 of the "@lens-protocol/react" package, when using the "useExplorePublications" hook with "sortCriteria: PublicationSortCriteria.Latest", there is an issue where the next page cannot be successfully requested.

### ISSUE THREAD

**Issue by jingledongding** [lens-protocol/lens-sdk#364]
```
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 97.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/jingxiaopeng/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
 code: 
```
  const {
    data: publications,
    loading,
    hasMore,
    next,
  } = useExplorePublications({
    limit: 20,
    timestamp: refreshTimestamp,
    sortCriteria: PublicationSortCriteria.Latest,
    publicationTypes: [PublicationTypes.Post],
  });
```

**Comment by jingledongding** [comment]
When I switch the sortCriteria filter to PublicationSortCriteria.TopCollected, everything works fine.

**Comment by cesarenaldi** [comment]
Hi @jingledongding , thank you for reporting this.

We recently promoted `1.1.0` to stable.. can you please try to upgrade and see if the problem persist?

From your description I am inclined to think of an API issue, but I wasn't able to reproduce anything from my testing.

In 1.1.0 we also introduced a `prev` callback which helps with retrieving newer results. Wondering if this could be of any help for your usage.

**Comment by jingledongding** [comment]
thanks for your gays do, I will try soon

**Comment by jingledongding** [comment]
@cesarenaldi  Hi,I have upgraded to version 1.1.0 and conducted a series of tests. It seems that the issue lies with the data returned on the first request, as it appears to be unexpected and prevents me from obtaining the next page of data. When I skip the hasMore check and directly make the next request, I am able to retrieve the data. However, this also prevents me from merging it with the cache. Additionally, if I make another next page request, it resets back to the initial pointer.

 first query:
`{
"operationName": "ExplorePublications",
"variables": {
"limit": 10,
"publicationTypes": [
"POST"
],
"sortCriteria": "LATEST",
"observerId": null,
"sources": [],
}
"query":{...},
}
`
response data:
`{
"data": {
"result":{
"item":[...],
"pageInfo": {
"__typename": "PaginatedResultInfo",
"prev": "{\"timestamp\":1,\"offset\":0}",
"next": "{\"timestamp\":1,\"offset\":10}",
"totalCount": null
},
"__typename": "ExplorePublicationResult",
}
}
}
`

**Comment by cesarenaldi** [comment]
Thank you @jingledongding for these details. We'll investigate further.

**Comment by jingledongding** [comment]
Thank you for your kind words. Keep up the great work!

**Comment by cesarenaldi** [comment]
> @cesarenaldi Hi,I have upgraded to version 1.1.0 and conducted a series of tests. It seems that the issue lies with the data returned on the first request, as it appears to be unexpected and prevents me from obtaining the next page of data. When I skip the hasMore check and directly make the next request, I am able to retrieve the data. However, this also prevents me from merging it with the cache. Additionally, if I make another next page request, it resets back to the initial pointer.
> 
> code: ` const { data: publications, loading, hasMore, next, } = useExplorePublications({ limit: 20, sortCriteria: PublicationSortCriteria.Latest, publicationTypes: [PublicationTypes.Post], })` first query: `{ "operationName": "ExplorePublications", "variables": { "limit": 10, "publicationTypes": [ "POST" ], "sortCriteria": "LATEST", "observerId": null, "sources": [], } "query":{...}, } ` response data: `{ "data": { "result":{ "item":[...], "pageInfo": { "__typename": "PaginatedResultInfo", "prev": "{\"timestamp\":1,\"offset\":0}", "next": "{\"timestamp\":1,\"offset\":10}", "totalCount": null }, "__typename": "ExplorePublicationResult", } } } `
> 
> **The following is an example of data that allows for a successful request for the next page.** code: ` const { data: latestCreateds, hasMore: latestHasMore, next: latestNext, } = useExploreProfiles({ sortCriteria: ProfileSortCriteria.LatestCreated, limit: 20, observerId: activeProfile?.id, })` query: `{ "operationName": "ExploreProfiles", "variables": { "limit": 20, "observerId": null, "sortCriteria": "LATEST_CREATED", "sources": [] }, "query":{...}, } ` response data: `{ "data": { "result":{ "item":[...], "pageInfo": { "__typename": "PaginatedResultInfo", "prev": "{\"offset\":0}", "next": "{\"offset\":20}", "totalCount": 117761 }, "__typename": "ExploreProfileResult" } } } `
> 
> I'm not familiar with the repository and don't know what's happening internally. Can you help me take a look, please?

@jingledongding I was looking at your examples again and there's 2 question I have.

The first one is:

are you sure the query for the first call belongs to the use of `useExploreProfiles` few lines above? I see the `limit` in the `useExploreProfiles` call is set to 20 but the query has 10.

Also is it possible in your tests you are calling `next` "too early", before the initial request `loading` transitioned from `true` to `false`?

**Comment by melissafzhang** [comment]
Potentially related but we're also experiencing issues with `usePublications` hook where `hasMore` is always `false` even though the first query has `pageInfo.next` defined.

```
const LensFeed = ({ profileId }: { profileId: ProfileId }) => {
  const {
    data: publications,
    hasMore,
    next,
    loading,
  } = usePublications({
    profileId,
    limit: 10,
  });

  return (
    <div className={styles.feed}>
      {publications?.map((post) => (
        <LensPost publicationID={post.id} key={post.id} />
      ))}
      {hasMore && (
        <Button onClick={next} buttonType="modeOnBackground" loading={loading}>
          See More
        </Button>
      )}
    </div>
  );
};

**Comment by krzysu** [comment]
I think this issue is related to https://github.com/lens-protocol/lens-sdk/issues/382 and there is a fix in v.1.1.1 that was released today, @jingledongding could you try if the v1.1.1 works for you?

**Comment by krzysu** [comment]
then I'm closing this issue, thanks all for your participation!
