### ISSUE TITLE
Support wagmi v1

### ISSUE THREAD

**Issue by kasparkallas** [lens-protocol/lens-sdk#379]
**Problem**
Wagmi had a major milestone with the release of v1 (currently `1.1.0`), and there's no point in staying on `0.12.13`. Projects using `wagmi 0.12.13` should transition to v1, which replaces `ethers` with `viem`.

**Solution**
* Provide a concise guide for using with `wagmi` v1 and `viem`.
* `@lens-protocol/wagmi`  should change the peerDependency from ^0.12.13 to ^1.0.0.

See the `viem` documentation: https://viem.sh/docs/ethers-migration.html

A discussion on `ethers` interoperability in the `wagmi` git repository: https://github.com/wagmi-dev/wagmi/discussions/2340

**Alternatives**
Long-term, it's essential to move to `viem` as staying with wagmi `0.12.13` will lead to hard to debug issues and missing out on important improvements.

**Additional context**
The `ethersWalletToAccount` adapter can facilitate the `ethers` to `viem` transition: https://viem.sh/docs/migration-guide.html#for-ethers-wallet-adapter-use-etherswallettoaccount

Happy to help out to speed up the upgrade!

**Comment by cesarenaldi** [comment]
Hey @kasparkallas we are looking into it these days. You can see a draft PR in progress here: https://github.com/lens-protocol/lens-sdk/pull/380

We should have something more concrete next week.
