### ISSUE TITLE
usePollDetails --> When there is a risk of snapshotting potentially volatile voting details, accessing the voting information becomes unreliable, and it may lead to a potential crash of the shared kernel.

### ISSUE THREAD

**Issue by jingledongding** [lens-protocol/lens-sdk#425]
**Describe the bug**

usePollDetails:
When there is a risk of snapshotting potentially volatile voting details, accessing the voting information becomes unreliable, and it may lead to a potential crash of the shared kernel.
**To Reproduce**

`
  const {data} = usePollDetails({
    publication: {
      __typename: 'Post',
      id: '0x3d0f-0x01dc',
      stats: {
        __typename: 'PublicationStats',
        totalAmountOfMirrors: 0,
        totalUpvotes: 0,
        totalDownvotes: 0,
        totalAmountOfCollects: 0,
        totalAmountOfComments: 0,
        commentsCount: 0,
      },
      metadata: {
        __typename: 'MetadataOutput',
        animatedUrl: null,
        contentWarning: null,
        description: null,
        image: null,
        locale: 'mt',
        mainContentFocus: 'TEXT_ONLY',
        name: 'Post by @xiaoqiecf5e.lens',
        media: [],
        attributes: [
          {
            __typename: 'MetadataAttributeOutput',
            traitType: 'type',
            value: 'text_only',
          },
        ],
        encryptionParams: null,
        tags: ['business_&_entrepreneurs'],
      },
      profile: {
        __typename: 'Profile',
        id: '0x3d0f',
        name: 'xiaoqiecf5e ◱ ◱',
        bio: 'xiaoqie is the best  yyds',
        handle: 'xiaoqiecf5e.lens',
        ownedBy: '0x15d693444ABd97710437de8B9Bc271137994cf5e',
        interests: [
          'ART_ENTERTAINMENT__DESIGN',
          'ART_ENTERTAINMENT__MUSIC',
          'BUSINESS__CREATOR_ECONOMY',
          'CAREER',
          'EDUCATION',
          'FOOD_DRINK__COOKING',
          'HEALTH_FITNESS__BIOHACKING',
          'HOBBIES_INTERESTS__SPORTS',
          'LAW_GOVERNMENT_POLITICS__REGULATION',
          'LENS',
          'NEWS',
          'TECHNOLOGY__SCIENCE',
        ],
        picture: {
          __typename: 'MediaSet',
          original: {
            __typename: 'Media',
            altTag: null,
            cover: null,
            mimeType: null,
            url: 'https://ik.imagekit.io/lens/media-snapshot/394954b96a3daefc5203017bdb3c33344ec760885030eb431327fd24e709bc44.jpg',
          },
        },
        coverPicture: {
          __typename: 'MediaSet',
          original: {
            __typename: 'Media',
            altTag: null,
            cover: null,
            mimeType: null,
            url: 'https://lens.infura-ipfs.io/ipfs/QmPSyEJYc481LcddQWXx8bK3xHzShfz9R1chZWZLtJH3XG',
          },
        },
        stats: {
          __typename: 'ProfileStats',
          totalCollects: 15,
          totalComments: 51,
          totalFollowers: 51,
          totalFollowing: 291,
          totalMirrors: 221,
          totalPosts: 206,
          totalPublications: 478,
          commentsCount: 0,
          postsCount: 0,
          mirrorsCount: 0,
        },
        followModule: null,
        followPolicy: {
          type: 'ANYONE',
        },
        __attributes: [
          {
            __typename: 'Attribute',
            displayType: null,
            key: 'location',
            value: 'gzhou',
          },
          {
            __typename: 'Attribute',
            displayType: null,
            key: 'website',
            value: 'https://land.philand.xyz/xiaoqie.eth',
          },
          {
            __typename: 'Attribute',
            displayType: null,
            key: 'twitter',
            value: 'xianshengxiong1',
          },
          {
            __typename: 'Attribute',
            displayType: null,
            key: 'hasPrideLogo',
            value: 'true',
          },
          {
            __typename: 'Attribute',
            displayType: null,
            key: 'statusEmoji',
            value: '😍',
          },
          {
            __typename: 'Attribute',
            displayType: null,
            key: 'statusMessage',
            value: 'love',
          },
          {
            __typename: 'Attribute',
            displayType: null,
            key: 'app',
            value: 'Lenster',
          },
        ],
        attributes: {
          location: {
            attribute: {
              __typename: 'Attribute',
              displayType: null,
              key: 'location',
              value: 'gzhou',
            },
          },
          website: {
            attribute: {
              __typename: 'Attribute',
              displayType: null,
              key: 'website',
              value: 'https://land.philand.xyz/xiaoqie.eth',
            },
          },
          twitter: {
            attribute: {
              __typename: 'Attribute',
              displayType: null,
              key: 'twitter',
              value: 'xianshengxiong1',
            },
          },
          hasPrideLogo: {
            attribute: {
              __typename: 'Attribute',
              displayType: null,
              key: 'hasPrideLogo',
              value: 'true',
            },
          },
          statusEmoji: {
            attribute: {
              __typename: 'Attribute',
              displayType: null,
              key: 'statusEmoji',
              value: '😍',
            },
          },
          statusMessage: {
            attribute: {
              __typename: 'Attribute',
              displayType: null,
              key: 'statusMessage',
              value: 'love',
            },
          },
          app: {
            attribute: {
              __typename: 'Attribute',
              displayType: null,
              key: 'app',
              value: 'Lenster',
            },
          },
        },
        dispatcher: {
          __typename: 'Dispatcher',
          address: '0xca674628a04dA98D12147EF8bE7c3663bc0820Ff',
          canUseRelay: true,
        },
        onChainIdentity: {
          __typename: 'OnChainIdentity',
          proofOfHumanity: false,
          ens: {
            __typename: 'EnsOnChainIdentity',
            name: 'xiaoqie.eth',
          },
          sybilDotOrg: {
            __typename: 'SybilDotOrgIdentity',
            verified: false,
            source: {
              __typename: 'SybilDotOrgIdentitySource',
              twitter: {
                __typename: 'SybilDotOrgTwitterIdentity',
                handle: null,
              },
            },
          },
          worldcoin: {
            __typename: 'WorldcoinIdentity',
            isHuman: false,
          },
        },
        isFollowedByMe: false,
        isFollowingObserver: false,
        followStatus: null,
        ownedByMe: false,
      },
      collectedBy: null,
      collectModule: {
        __typename: 'RevertCollectModuleSettings',
        contractAddress: '0xa31FF85E840ED117E172BC9Ad89E55128A999205',
      },
      collectNftAddress: null,
      referenceModule: null,
      createdAt: '2023-07-17T13:33:05.000Z',
      hidden: false,
      isGated: false,
      reaction: null,
      hasCollectedByMe: false,
      canComment: {
        __typename: 'CanCommentResponse',
        result: false,
      },
      canMirror: {
        __typename: 'CanMirrorResponse',
        result: false,
      },
      mirrors: [],
      canObserverDecrypt: {
        __typename: 'CanDecryptResponse',
        result: false,
        reasons: ['MISSING_ENCRYPTION_PARAMS'],
      },
      hasOptimisticCollectedByMe: false,
      isOptimisticMirroredByMe: false,
      isMirroredByMe: false,
      collectPolicy: {
        type: 'NO_COLLECT',
        state: 'CANNOT_BE_COLLECTED',
      },
      referencePolicy: {
        type: 'ANYONE',
      },
      decryptionCriteria: null,
      contentInsight: {
        type: 'SNAPSHOT_POLL',
        spaceId: 'lido-snapshot.eth',
        proposalId:
          '0xbf00c00a2e9c009e9d014e1ed4885d2b77d525ffb1c7495479f750a915f30f2e',
        url: 'https://snapshot.org/#/lido-snapshot.eth/proposal/0xbf00c00a2e9c009e9d014e1ed4885d2b77d525ffb1c7495479f750a915f30f2e',
      },
    },
  });
`
**Expected behaviuor**

InvariantError: Snapshot proposal must have at least two choices

**If using the React bindings, what is the essence of your React app?**
- [ ] React Web App
- [ ] React Native 

**Version of the packages you are using**
Please provide the version of the packages.

**Additional context**

**Comment by cesarenaldi** [comment]
Hi @jingledongding thank you for reporting this.

Can I please ask you some clarifications?

> When there is a risk of snapshotting potentially volatile voting details, accessing the voting information becomes unreliable, and it may lead to a potential crash of the shared kernel.

Can you please expand on what you mean by "there is a risk of snapshotting potentially volatile voting details"?

What makes it volatile? Was the proposal definition amended while you where testing the hook?

**Comment by jingledongding** [comment]
When I access https://snapshot.org/#/lido-snapshot.eth/proposal/0xbf00c00a2e9c009e9d014e1ed4885d2b77d525ffb1c7495479f750a915f30f2e, Snapshot doesn't redirect to the correct page. 
![image](https://github.com/lens-protocol/lens-sdk/assets/107233143/e31b6d22-5fab-42ed-9ad4-76f99478e3fc)

**Comment by cesarenaldi** [comment]
I've noticed the same warning on the Snapshot UI... never seen it before.
Seems a spam prevention feature of Snapshot UI itself.

Is the Snapshot URL correct? Is this a legitimate Proposal?

In order to integrate with Snapshot the Lens SDK hook does not access the same HTML page you open with the browser but instead extracts the Proposal Id and Space Id and uses Snapshot GQL APIs to retrieve the relevant details.

**Comment by jingledongding** [comment]
**Is the Snapshot URL correct?**
this url is from @lensprotocol/react, so I think it's correct
 **Is this a legitimate Proposal?**
It's possible that only someone with access to the snapshot would know this, but based on the information available, the proposal appears to be sensitive."

**Comment by cesarenaldi** [comment]
Fix coming soon: https://github.com/lens-protocol/lens-sdk/pull/456

**Comment by cesarenaldi** [comment]
This is now available in:
- `@lens-protocol/react@next`
- `@lens-protocol/react-web@next`
- `@lens-protocol/client@next`

It will be released `1.3` stable next week.
