### ISSUE TITLE
unFollow not working

### ISSUE THREAD

**Issue by jsonpreet** [lens-protocol/lens-sdk#435]
**Describe the bug**
unFollow hook returns two types errors:

`{"data":{"result":{"__typename":"RelayError","reason":"NOT_ALLOWED"}}}`

OR

`{"data":{"result":{"id":"d7f1958c-a283-4bc2-8415-932d07757198","expiresAt":"2023-07-19T06:07:35.000Z","typedData":{"types":{"BurnWithSig":[{"name":"tokenId","type":"uint256","__typename":"EIP712TypedDataField"},{"name":"nonce","type":"uint256","__typename":"EIP712TypedDataField"},{"name":"deadline","type":"uint256","__typename":"EIP712TypedDataField"}],"__typename":"CreateBurnEIP712TypedDataTypes"},"domain":{"__typename":"EIP712TypedDataDomain","name":"shefi.lens-Follower","chainId":137,"version":"1","verifyingContract":"0x993c359316A1E293F6A7d54a62A183C6034A8cF3"},"message":{"nonce":0,"deadline":1689746855,"tokenId":"0x1568","__typename":"CreateBurnEIP712TypedDataValue"},"__typename":"CreateBurnEIP712TypedData"},"__typename":"CreateUnfollowBroadcastItemResult"}}}`

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App

**Version of the packages you are using**
1.2.1

**Comment by cesarenaldi** [comment]
@jsonpreet I see you request is on Polygon Mainnet. I assume your `LensConfig.environment: production`. Is your domain whitelisted to use the dispatcher?

The `NOT_ALLOWED` is the typical API response that informs one cannot use gasless tx via the Lens API.

If this is an app in development and you are making requests from `localhost` to production Lens API, this is likely the case.

My recommendation is to always use `development` environment during the development phase and have your production deployment only use the `production` environment configuration.

**Comment by jsonpreet** [comment]
Oh Okay Thank You Sir
