### ISSUE TITLE
Comments and useFeed/usePublication

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#452]
**Describe the bug**
Comments returned from `useFeed` (`feed` api endpoint) don't contain the `commentOn` property because it's not needed in that context. However, due to the caching in the SDK, subsequent calls to `usePublication` for one of those comments will return the local cached Comment that doesn't include `commentOn` so the comment cannot be displayed properly.

**To Reproduce**
You can reproduce this on Buttrfly Web. Once you sign in, go to your home feed. You'll see some comments displayed with their parent post, but if you press on a comment to go to the full post screen, the comment will not show the post it was in response to (because of the missing `commentOn` property). If you do a full refresh on that page, then you'll see the comment and it's parent post displayed properly.

**Expected behaviuor**
I expect calling `usePublication` on a comment to always return a comment with a `commentOn` property.

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App

**Version of the packages you are using**
1.2.2

**Comment by cesarenaldi** [comment]
Thank you @moesalih ,

we isolated the issue... we are testing a fix as we speak. Will let you know when fixed (wither API or via SDK).

**Comment by cesarenaldi** [comment]
An update on this. The underlying issue is an inconsistency in the API. The fix we are testing remove the restriction that omits `commentOn` from Comment when returned as part of `FeedItem`.

Given we are in the thick of API changes to support Lens v2. I'll check with Josh if we can squeeze into an API release next week.

**Comment by cesarenaldi** [comment]
@moesalih wondering... with `usePublication` now fetching new data on render (no matter of cache content). Could the use of `usePublication` a good workaround until we fix this at the API level?

**Comment by moesalih** [comment]
@cesarenaldi Yeah the new `usePublication` behavior is enough of a workaround for now until the issue can be fixed in the api.

**Comment by cesarenaldi** [comment]
Brilliant, thank you @moesalih for checking. Closing this issue then. Lens v2 will not be affected by this issue.
