### ISSUE TITLE
Publication appId

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#453]
**Describe the bug**
Publications returned from the SDK don't include the `appId` property.

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App

**Version of the packages you are using**
1.2.2

**Comment by cesarenaldi** [comment]
Fix landing soon: https://github.com/lens-protocol/lens-sdk/pull/458

**Comment by cesarenaldi** [comment]
This is now available in:
- `@lens-protocol/react@next`
- `@lens-protocol/react-web@next`
- `@lens-protocol/client@next`

It will be released `1.3` stable next week.
