### ISSUE TITLE
useCreateComment broadcast error "Not_Allowed"

### ISSUE THREAD

**Issue by jsonpreet** [lens-protocol/lens-sdk#462]
**Describe the bug**
Hi, Sometime, i am getting error from useCreateComment hook.

Error: BroadcastingError: broadcasting failed with reason: NOT_ALLOWED

Request:

`{"operationName":"CreateCommentTypedData","variables":{"request":{"contentURI":"https://arweave.net/5i4txx46U0FqKpRVcCN6IrFvrdrv818EuoamVPXXIRI","profileId":"0x016efc","publicationId":"0xf6b0-0x017d","collectModule":{"revertCollectModule":true}}},"query":"mutation CreateCommentTypedData($request: CreatePublicCommentRequest!, $options: TypedDataOptions) {\n  result: createCommentTypedData(request: $request, options: $options) {\n    id\n    expiresAt\n    typedData {\n      ...CreateCommentEIP712TypedData\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CreateCommentEIP712TypedData on CreateCommentEIP712TypedData {\n  types {\n    CommentWithSig {\n      name\n      type\n      __typename\n    }\n    __typename\n  }\n  domain {\n    ...EIP712TypedDataDomain\n    __typename\n  }\n  message: value {\n    nonce\n    deadline\n    profileId\n    contentURI\n    profileIdPointed\n    pubIdPointed\n    collectModule\n    collectModuleInitData\n    referenceModuleData\n    referenceModule\n    referenceModuleInitData\n    __typename\n  }\n  __typename\n}\n\nfragment EIP712TypedDataDomain on EIP712TypedDataDomain {\n  __typename\n  name\n  chainId\n  version\n  verifyingContract\n}"}`

Response:

`{"data":{"result":{"id":"626145e0-99e0-4aac-a755-5418c32545a6","expiresAt":"2023-07-31T07:13:54.000Z","typedData":{"types":{"CommentWithSig":[{"name":"profileId","type":"uint256","__typename":"EIP712TypedDataField"},{"name":"contentURI","type":"string","__typename":"EIP712TypedDataField"},{"name":"profileIdPointed","type":"uint256","__typename":"EIP712TypedDataField"},{"name":"pubIdPointed","type":"uint256","__typename":"EIP712TypedDataField"},{"name":"referenceModuleData","type":"bytes","__typename":"EIP712TypedDataField"},{"name":"collectModule","type":"address","__typename":"EIP712TypedDataField"},{"name":"collectModuleInitData","type":"bytes","__typename":"EIP712TypedDataField"},{"name":"referenceModule","type":"address","__typename":"EIP712TypedDataField"},{"name":"referenceModuleInitData","type":"bytes","__typename":"EIP712TypedDataField"},{"name":"nonce","type":"uint256","__typename":"EIP712TypedDataField"},{"name":"deadline","type":"uint256","__typename":"EIP712TypedDataField"}],"__typename":"CreateCommentEIP712TypedDataTypes"},"domain":{"__typename":"EIP712TypedDataDomain","name":"Lens Protocol Profiles","chainId":137,"version":"1","verifyingContract":"0xDb46d1Dc155634FbC732f92E853b10B288AD5a1d"},"message":{"nonce":45,"deadline":1690787634,"profileId":"0x016efc","contentURI":"https://arweave.net/5i4txx46U0FqKpRVcCN6IrFvrdrv818EuoamVPXXIRI","profileIdPointed":"0xf6b0","pubIdPointed":"0x017d","collectModule":"0xa31FF85E840ED117E172BC9Ad89E55128A999205","collectModuleInitData":"0x","referenceModuleData":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000","referenceModule":"0x0000000000000000000000000000000000000000","referenceModuleInitData":"0x","__typename":"CreateCommentEIP712TypedDataValue"},"__typename":"CreateCommentEIP712TypedData"},"__typename":"CreateCommentBroadcastItemResult"}}}`

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App

**Version of the packages you are using**
 "@lens-protocol/client": "^1.2.0",
 "@lens-protocol/react-web": "^1.2.2",
 "@lens-protocol/wagmi": "^2.0.1"

**Comment by cesarenaldi** [comment]
`NOT_ALLOWED` is a server error at broadcast time signalling that the calling domain is not whitelisted for gasless tx.

Is it possible you switched to `production` environment but making request from a development instance (e.g. from `localhost`)?

This does not happen on `development` environment, so during development we strongly advise to use `development` for several reasons, among which
- Activities done through a Lens Profile impact the ML logic that determine the "signal score" of a Profile. As real Lens Profile are limited during the closed beta period, any test done against production risks to impact your own real Profile signal score.
- Test activities often produce low quality content that impact adversely the entire ecosystem.

**Comment by jsonpreet** [comment]
Ok thanks
