### ISSUE TITLE
Get accessToken of current user

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#474]
**Is your feature request related to a problem? Please describe.**
Is there a way to get the Lens API `accessToken` of the current authenticated user? Can this be added?

**Describe the solution you'd like**
I would like a function or hook to return the accessToken.

**Comment by cesarenaldi** [comment]
We contemplated this ourself for some of our internal use of the SDK.

We can surely add this.

**Comment by cesarenaldi** [comment]
Coming soon: https://github.com/lens-protocol/lens-sdk/blob/d53f4587c017d558e230161929f0c631538683da/packages/react/src/experimental/useAccessToken.ts

**Comment by cesarenaldi** [comment]
@moesalih can you please give it a try in latest `next` tag? Namely `@lens-protocol/react-web@1.3.0-next.5`

There is a new `useAccessToken` experimental hook available.
