### ISSUE TITLE
`sources` and `profileIds` missing from `useExplorePublications` request 

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#490]
**Describe the bug**
`sources` and `profileIds` missing from `useExplorePublications` request 

react-web 1.3.0-next

**Comment by cesarenaldi** [comment]
I am going to add `profileIds` in the next release.

Regarding `sources`... I can see it working in my example. Are you providing it as part of the `LensConfig`?

**Comment by moesalih** [comment]
No i'm not providing it part of LensConfig. I only want to provide it to one useExplorePublications request, not the entire sdk.

**Comment by cesarenaldi** [comment]
Got it.

Overriding sources on a call base is a change we had planned already. It will definitely be part of Lens SDK v2 but cannot guarantee we can work on it earlier.

I would need to get back to you on this next week.

**Comment by moesalih** [comment]
@cesarenaldi just noticed that `useExplorePublications` is also missing the `noRandomize` option

**Comment by cesarenaldi** [comment]
@moesalih adding `noRandomize` and `sources` override option. Just noticing that `explorePublications` does not accept `profileIds`.

**Comment by cesarenaldi** [comment]
`noRandomize ` and `sources` override option is now available in `1.3-next.8` can you please update and confirm works as intended so we can close this issue?
