### ISSUE TITLE
useCreatePost with timed collects causes an error on CreatePostTypedData

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#498]
**Describe the bug**
setting `endTimestamp` when creating a post causes an api error on the `CreatePostTypedData` endpoint when the dispatcher is not allowed and we're trying to do a self funded fallback. The error is: 
`UnspecifiedError: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.6.2)`

the `endTimestamp` value i'm providing is a number as required by the sdk, example: `1692201833189`

I noticed that the sdk is sending the endTimestamp to the api as a string, for example: `"1692201833189"`, so as a workaround i tried to provide an ISO string for the endTimestamp like `"2023-08-16T16:33:02.277Z"` like i do in the mobile app, and that seems to work for simple collects, but for multi recipient collects, i get another error from the sdk and not from the api: 
```
error InvariantError: fix the following issues
· "collect" expected to match one of the following groups:
		· "collect.recipient": Required
	OR:
		· "collect.endTimestamp": Expected number, received string
	OR:
		· "collect.recipient": Required
		· "collect.vault": Required
		· "collect.endTimestamp": Expected number, received string
	OR:
		· "collect.recipient": Required
		· "collect.depositToAave": Invalid literal value, expected true
		· "collect.endTimestamp": Expected number, received string
	OR:
		· "collect.type": Invalid literal value, expected "FREE"
	OR:
		· "collect.type": Invalid literal value, expected "NO_COLLECT"
```

**Version of the packages you are using**
react-web 1.3 next.9

**Comment by cesarenaldi** [comment]
hey @moesalih this is an interesting one.

There has been some inconsistencies in the way Lens API ingest/produce Date and timestamps across different queries/mutations so cannot exclude the SDK got caught up in one of these and is asking for date in the wrong format.

Let me run some tests and get back to you on this one.

**Comment by cesarenaldi** [comment]
This is all being rewritten in v2. What used to be timestamps are all now date times. Closing this issue for now.
