### ISSUE TITLE
`usePublications` missing `publicationIds` request param

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#500]
**Describe the bug**
`usePublications` missing `publicationIds` request param

react-web 1.3-next.9

**Comment by cesarenaldi** [comment]
https://github.com/lens-protocol/lens-sdk/pull/503

**Comment by desfero** [comment]
@moesalih `publicationIds` is now available under `usePublications` under `1.3.1-next.1`. 
Can you please update and confirm if that works as intended so we can close the issue?

**Comment by moesalih** [comment]
@desfero yup works now. thanks.

**Comment by moesalih** [comment]
@desfero actually found an issue with this. the first `usePublications` with `publicationIds` gets cached and if the `publicationIds` are changed then no requests are sent and the same old result is returned which is invalid. So I need to be able to change the `publicationIds`. cc @cesarenaldi

**Comment by desfero** [comment]
@moesalih Good catch 🏅. Should be fixed on `1.3.1-next.2`. Sorry for inconvenience.
