### ISSUE TITLE
Expose Apollo client in Lens Client SDK

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#551]
I'd like to have access to the authenticated Apollo Client used in the Lens Client SDK to do custom graphql queries and mutations that are not directly supported by the sdk, similar to how the Lens React SDK has a `useApolloClient` hook.

can this be added?

**Comment by cesarenaldi** [comment]
For posterity, as mentioned in DM, I understand you found the methods you were specifically looking for, but if something is missing from the `LensClient` is likely an oversight more than the desire to not expose it. So feel free to report in a GH what you think is missing.

Closing this for now.
