### ISSUE TITLE
Lens V2 client alpha 7 issue explore publications

### ISSUE THREAD

**Issue by mvanhalen** [lens-protocol/lens-sdk#559]
**Describe the bug**
A internal server error happens when calling Explore publications with the Lens V2 Alpha 7 client.

`{
    "errors": [
        {
            "message": "Cannot read properties of undefined (reading 'toLocaleLowerCase')",
            "locations": [
                {
                    "line": 36,
                    "column": 3
                }
            ],
            "path": [
                "result",
                "items",
                9,
                "metadata"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "TypeError: Cannot read properties of undefined (reading 'toLocaleLowerCase')",
                        "    at new Locale (/usr/src/app/packages/custom-types-shared/lib/locale.type.js:19:22)",
                        "    at PublicationMetadataRedisCacheStorage.get (/usr/src/app/packages/api-lens/lib/publication/cache/metadata.js:27:38)",
                        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                        "    at async getPublicationMetadata (/usr/src/app/packages/api-lens/lib/publication/operations/metadata/get-publication-metadata.js:7:27)",
                        "    at async PublicationPostFieldResolver.metadata (/usr/src/app/packages/api-lens/lib/publication/resolvers/field-resolvers/publication.js:56:28)"
                    ]
                }
            }
        }
    ],
    "data": null
}`
 

**To Reproduce**
Call the the function like this:

`
 const query = {where:{publicationTypes:[ExplorePublicationType.Post],
          metadata:{mainContentFocus:mediaFilter}},
          orderBy:ExplorePublicationsOrderByType.LensCurated,limit:LimitType.TwentyFive,
          cursor:null
      };

lensClient.explore.publications(query)`
``

**Expected behavior**
No error

**Version of the packages you are using**
Lens v2 client 2.0.0-alpha.7

**Additional context**
Was working with previous Alpha

**Comment by cesarenaldi** [comment]
For posterity this was a cache issue. Now solved. Looking into a non-related issue that seems to be blocking some queries. Reference module related.
