### ISSUE TITLE
Cannot use LensClient in a Chrome Extension

### ISSUE THREAD

**Issue by iPaulPro** [lens-protocol/lens-sdk#606]
**Describe the bug**
I'm trying to use the `LensClient` for V2 in a Chrome Extension but I received this error when attempting to query profiles:

```
{
  "message": "Context creation failed: Invalid url protocol chrome-extension:. Should be https:, value: chrome-extension://iebmcaohopockfafpfoeoaopihocflci",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR",
    "exception": {
      "stacktrace": [
        "Error: Context creation failed: Invalid url protocol chrome-extension:. Should be https:, value: chrome-extension://iebmcaohopockfafpfoeoaopihocflci",
        "    at URL.validate (/usr/src/app/packages/custom-types-shared/lib/url.type.js:38:19)",
        "    at new BaseType (/usr/src/app/packages/custom-types-shared/lib/base-types/base-type.js:9:14)",
        "    at new StringType (/usr/src/app/packages/custom-types-shared/lib/base-types/string.type.js:10:9)",
        "    at new URI (/usr/src/app/packages/custom-types-shared/lib/uri.type.js:14:9)",
        "    at new URL (/usr/src/app/packages/custom-types-shared/lib/url.type.js:7:9)",
        "    at getOriginFromRequest (/usr/src/app/packages/apollo-server-shared/lib/middleware/get-origin-from-request.js:8:16)",
        "    at ApolloServer.context (/usr/src/app/packages/api-lens/lib/api-setup/api.js:75:83)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
      ]
    }
  }
}
```

**To Reproduce**
I've only tried using `LensClient.profile.fetchAll()` but I assume this would be the error for all functions hitting the API. To reproduce use the `LensClient` from a Chrome Extension.

**Expected behaviuor**
The `LensClient` should allow requests from `chrome-extension:` protocol origins, as well as other browser extension protocols, like `moz-extension:`.

**Version of the packages you are using**
@lens-protocol/client: 2.0.0-alpha.11

**Comment by cesarenaldi** [comment]
Seems API related... let me relay this internally.

**Comment by iPaulPro** [comment]
> Seems API related... let me relay this internally.

Thanks! Note that I have no issues hitting the API directly from an extension and Focalize (the extension in question) has been whitelisted for dispatcher using a chrome-extension:// origin for a while.

**Comment by cesarenaldi** [comment]
I understand there was an issue with the API. A fix was deployed 1 hour or so ago. Can you please try again and let us know?

**Comment by iPaulPro** [comment]
🙏 Thanks for the quick turnaround! It's working now.
