### ISSUE TITLE
Update @lens-protocol/metadata version in @lens-protocol/client

### ISSUE THREAD

**Issue by jsonpreet** [lens-protocol/lens-sdk#607]
**Describe the bug**
I am getting error of version conflict installing @lens-protocol/react-web and @lens-protocol/client alpha versions

**To Reproduce**
Can you please update @lens-protocol/metadata@"0.1.0-alpha.29 to @lens-protocol/metadata@"0.1.0-alpha.30 under @lens-protocol/client?

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App
- [ ] React Native 

**Version of the packages you are using**
"@lens-protocol/client": "^2.0.0-alpha.11",
"@lens-protocol/react-web": "^2.0.0-alpha.7",
"@lens-protocol/wagmi": "^3.0.0-alpha.4"

<img width="817" alt="image" src="https://github.com/lens-protocol/lens-sdk/assets/26606638/417060e8-c388-4e38-86e9-255a4d3ccd04">

**Comment by cesarenaldi** [comment]
Thank you for reporting... will do for the next alpha build. We should move to ranges as soon as `@lens-protocol/metadata` moves to stable.

In the meantime are you ok to force it to latest via [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) so to unblock you in the immediate.

**Comment by cesarenaldi** [comment]
Fixed w/ latest alpha build.
