### ISSUE TITLE
Error in publications fetch with lens client 2.0.0-alpha.14

### ISSUE THREAD

**Issue by mvanhalen** [lens-protocol/lens-sdk#632]
**Describe the bug**
An error occurs for the following query:

`
query Publications

{
  "where": {
    "withOpenActions": [
      {
        "address": "0xfF824aB2FCb6986e399B5Af922c4a20778a047A1",
        "category": "COLLECT"
      }
    ]
  },
  "orderBy": "LATEST",
  "limit": "TwentyFive"
}
`

The error is:
`
{
    "errors": [
        {
            "message": "[CanDecrypt] Publication metadata not found for 0x33-0x0261} - [getPublicationMetadata] Could not find metadata context for publication 0x33-0x0261 - fix the following issues\n· \"version\": Required - SHOULD NEVER HAPPEN!",
            "locations": [
                {
                    "line": 444,
                    "column": 3
                }
            ],
            "path": [
                "result",
                "items",
                1,
                "operations",
                "canDecrypt"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "apollo": false,
                    "statusCode": 500,
                    "stacktrace": [
                        "Error: [CanDecrypt] Publication metadata not found for 0x33-0x0261} - [getPublicationMetadata] Could not find metadata context for publication 0x33-0x0261 - fix the following issues",
                        "· \"version\": Required - SHOULD NEVER HAPPEN!",
                        "    at PublicationOperationsFieldResolver.canDecrypt (/usr/src/app/packages/api-lens/lib/publication/resolvers/field-resolvers/publication-operations.js:191:19)",
                        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
                    ]
                }
            }
        }
    ],
    "data": null
}
`

**To Reproduce**
Happens each time.

**Expected behaviuor**
No errors

**Version of the packages you are using**
lens client 2.0.0-alpha.14

**Comment by cesarenaldi** [comment]
This was an API issue which got resolved. Please reopen if experience this again.
