### ISSUE TITLE
Unable to retrieve the latest publication. @lens-protocol/react":1.3.1 

### ISSUE THREAD

**Issue by jingledongding** [lens-protocol/lens-sdk#708]
**Describe the bug**
Hello, I'm using the V1 version of the Lens Protocol SDK for my React Native project. However, at some point, I noticed that all my data requests seem to be stuck within a fixed time range. Regardless of how I make requests, I'm unable to fetch real-time on-chain data. This is causing me some distress. Could you please help me investigate what might be the issue? The SDK version I'm currently using is "@lens-protocol/react": "^1.3.1".
———The current state lacks a profileId.
———So far, I haven't been fortunate enough to obtain a profile.LOL

**To Reproduce**
  ```
 const {
      data: publications,
      loading,
      hasMore,
      next,
    } = useExplorePublications({
      limit: 20,
      sortCriteria: PublicationSortCriteria.Latest,
      publicationTypes: [PublicationTypes.Post],
    });
```

**Expected behaviuor**

**If using the React bindings, what is the essence of your React app?**
- [ ] React Web App
- [☑️] React Native 

**Version of the packages you are using**
"@lens-protocol/react": "^1.3.1".

**Additional context**

**Comment by cesarenaldi** [comment]
@jingledongding the reason is the SDK 1.3 is bound to Lens API v1 that since the v2 migration (~2 weeks ago) is not in read-only mode.

To get new activities you need to migrate over to Lens SDK v2 which uses Lens API v2.

Let me know if you need some assistance in the process. Also we can move the conversation on Discord for a quicker turn around.

**Comment by jingledongding** [comment]
It seems that I have indeed encountered an issue. LOL
https://github.com/lens-protocol/lens-sdk/issues/741
