### ISSUE TITLE
Add WalletAuthetificationToProfileAuthetification to sdk

### ISSUE THREAD

**Issue by Watcher-eth** [lens-protocol/lens-sdk#769]
I am having issues with authentication when onboarding new wallets to Lens. Currently the WalletAuthetificationToProfileAuthetification only exists on the api and isn't exposed on the sdk. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cesarenaldi** [comment]
hey @Watcher-eth , can you please clarify if you mean `LensClient` SDK or Lens React SDK?

This feature is already present in React SDK under the hook: `useUpgradeCredentials`. You can see it in action [here](https://github.com/lens-protocol/lens-sdk/blob/develop/examples/web/src/misc/UseClaimHandle.tsx#L19).

**Comment by krzysu** [comment]
Hi @Watcher-eth.
The latest version of the LensClient contains the feature you requested. 
Upgrade to `@lens-protocol/client@2.0.0-alpha.25` and there you can use `client.authentication.upgradeCredentials` to achieve what you need. 
See the example here https://github.com/lens-protocol/lens-sdk/blob/develop/examples/node/scripts/authentication/upgradeCredentials.ts
