### ISSUE TITLE
Here is the diff that solved my problem:

### ISSUE THREAD

**Issue by jingledongding** [lens-protocol/lens-sdk#777]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@lens-protocol/storage@0.7.5-alpha.7` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@lens-protocol/storage/dist/lens-protocol-storage.cjs.dev.js b/node_modules/@lens-protocol/storage/dist/lens-protocol-storage.cjs.dev.js
index 9ba2eb6..0fc97f1 100644
--- a/node_modules/@lens-protocol/storage/dist/lens-protocol-storage.cjs.dev.js
+++ b/node_modules/@lens-protocol/storage/dist/lens-protocol-storage.cjs.dev.js
@@ -492,7 +492,7 @@ var Storage = /*#__PURE__*/function () {
               return this.provider.getItem(this.getStorageKey());
             case 2:
               json = _context5.sent;
-              if (!(json === null)) {
+              if (!(json === null || json === '')) {
                 _context5.next = 5;
                 break;
               }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by cesarenaldi** [comment]
hey @jingledongding, thank you for this. We will integrate it into a coming release.

**Comment by cesarenaldi** [comment]
@jingledongding this is now in the latest version of the SDKs.
