### ISSUE TITLE
It seems that the data provided by useOwnedHandles is not sufficiently real-time. I am unable to retrieve the profile I purchased through this hook.

### ISSUE THREAD

**Issue by jingledongding** [lens-protocol/lens-sdk#788]
**Describe the bug**
It seems that the data provided by useOwnedHandles is not sufficiently real-time. I am unable to retrieve the profile I purchased through this hook.

**To Reproduce**
`  const {data: infos} = useOwnedHandles({
    for: '0x1a4De364e26E9A822c42510206DFbDB13e5543Ea',
  });
`
![image](https://github.com/lens-protocol/lens-sdk/assets/107233143/6292d67f-8970-4034-9fbb-d99fdc0675d5)

**Expected behaviuor**

**If using the React bindings, what is the essence of your React app?**
- [ ] React Web App
![image](https://github.com/lens-protocol/lens-sdk/assets/107233143/9c87c76f-15d3-4f86-828b-67450b305ae9)

- [* ] React Native 

**Version of the packages you are using**
    "@lens-protocol/metadata": "^1.0.5",
    "@lens-protocol/react-native": "^0.1.0-alpha.2",
**Additional context**

**Comment by joshstevens19** [comment]
You only own a profile, not a handle they are 2 different things

That handle is owned by https://polygonscan.com/address/0xF4a0657b93f78Bf5F5387d1D391bf6361F7A7Fdc

that metadata in your wallet is out of date here one which is refreshed > https://opensea.io/assets/matic/0xdb46d1dc155634fbc732f92e853b10b288ad5a1d/36799

you brought the profile 10 days ago https://polygonscan.com/tx/0xeb887c4412bad6e1751cadef3c779a3f1794d46db125ccdef80d6649ffc24833 the handle will not follow it as they are 2 different NFTs

**Comment by jingledongding** [comment]
Thanks, Got it. lol
