### ISSUE TITLE
When I switch to a new wallet, LensProvider doesn't replace with the new signer. Can anyone help me look at this issue

### ISSUE THREAD

**Issue by jingledongding** [lens-protocol/lens-sdk#790]
**Describe the bug**
When I switch to a new wallet, LensP rovider doesn't replace with the new signer. Can anyone help me look at this issue

**To Reproduce**
`const InnerApp = () => {
  const bindings = useLensBindings();

  const lensConfig = useCallback(() => {
    return {
      bindings: bindings,
      // environment: development,
      environment: production,
      storage: lensStorage(),
    };
  }, [bindings]);
  return (
    <LensProvider config={lensConfig()}>
      <AppNavigator />
    </LensProvider>
  );
};

export function useLensBindings(): IBindings {
  const activeWallet = useSelector(activeGmWalletSelector);
  const provider = useMemo(() => {
    return new AlchemyProvider(
      'matic',
      `https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}`,
    );
  }, []);
  const wallet = useMemo(() => {
    if (activeWallet?.privateKey) {
      const wallet = new Wallet(activeWallet.privateKey, provider);
      return wallet;
    } else {
      return createHDWallet(provider);
    }
  }, [activeWallet, provider]);

  return {
    getProvider: async () => provider,
    getSigner: async () => wallet,
  };
}

`

**Expected behaviuor**
I've created multiple wallets in my app, and now I'm switching to another wallet, but the provider isn't switching to the corresponding signer

**If using the React bindings, what is the essence of your React app?**
- [ ] React Web App
- [* ] React Native 

**Version of the packages you are using**
    "@lens-protocol/metadata": "^1.0.5",
    "@lens-protocol/react-native": "^0.1.0-alpha.3",
    "react": "18.2.0",
    "react-native": "0.72.6",
**Additional context**

**Comment by cesarenaldi** [comment]
`<LensProvider>` does not support updating the `config`. This is to prevent accidental re-rendering to of the entire render tree given it is usually position quite high in the consumer's apps.

You can use an approach that keeps the bindings as a separate object and update it when needed. You can see how @bartomolina used this approach in the Lens PWA started app: https://github.com/bartomolina/lens-pwa/blob/main/lib/lens-privy-bindings.ts

**Comment by jingledongding** [comment]
Thank you very much, it worked.

**Comment by cesarenaldi** [comment]
Great, closing this issue then.
