### ISSUE TITLE
useSetProfileMetadata should update the profile cache returned by useSession

### ISSUE THREAD

**Issue by pradel** [lens-protocol/lens-sdk#797]
**Is your feature request related to a problem? Please describe.**

When updating profile metadata with useSetProfileMetadata, the profile returned by useSession is not updated, so one has to reload the page to see the changes in the app.

**Describe the solution you'd like**

The cache is updated so the views using the old metadata are updated with the new one

**Comment by cesarenaldi** [comment]
@pradel what you are describing seems an issue, the profile from the `useSession` should update seamlessly. Can you please clarify more about your setup? Are you waiting for the update until its completion (see example code [here](https://github.com/lens-protocol/lens-sdk/blob/develop/examples/web/src/profiles/UseSetProfileMetadata.tsx#L55))?

**Comment by pradel** [comment]
@cesarenaldi seems like I was missing the waitForCompletion, after adding it everything is working, thanks!
