### ISSUE TITLE
Add support for React suspense

### ISSUE THREAD

**Issue by pradel** [lens-protocol/lens-sdk#809]
**Is your feature request related to a problem? Please describe.**

It would be amazing to have this library expose the same queries as now but with suspense mode enabled.

**Comment by cesarenaldi** [comment]
Glad you raised this @pradel. It's something we've been thinking for quite some time and partially blocked by Apollo (which introduced support for Suspense only recently in 3.8).

**Comment by cesarenaldi** [comment]
@pradel there's 2 types of "loading phases" that could take advantage of Suspense in the SDK.

The first is about the bootstrap phase. When the app starts there is a period of time where the SDK does some checks, renews the access token, and finally update the UI state. This is mostly invisible to the end user as it's hidden behind the `useSession` `loading` flag.

The second one is about most of the async read processes (mostly read hooks such as `usePublications`, `useProfiles`, etc.).

Would you be be able to expand on your idea so to know better what is your ideal scenario?

**Comment by pradel** [comment]
As you described the ideal scenario for me is to have the following:
- A global Suspense around the user state to create a global loading screen until the user state is resolved (like Hey is doing).
- Suspense hooks to fetch the data from the Lens API like now

Don't think I need more tbh

**Comment by cesarenaldi** [comment]
For the global Suspense, would you you expect this to be embedded into the `<LensProvider>`:

```tsx
<LensProvider fallback={<Loading />}>
  // ...
</LensProvider>
```

or standalone?

**Comment by pradel** [comment]
I guess the following 2 options can work, maybe the second one is less "magic" and easier to understand?
```tsx
<LensProvider fallback={<Loading />}>
  // ...
</LensProvider>

<Suspense fallback={<Loading />}>
  <LensProvider>
    // ...
  </LensProvider>
</Suspense>
```

**Comment by cesarenaldi** [comment]
Yeah, I like the 2nd approach too. I guess we would need to have an opt-in mechanism for Suspense enabled `<LensProvider>` (for bootstrap phase) and for hooks. I can see this working in many ways but would love to have some feedback.

We could have a `suspense` flag in the `LensConfig` and from the point on the `<LensProvider>` and any hook would support Suspense.

Alternative we can control it with a flag on a case-by-case.

WDYT?

**Comment by pradel** [comment]
for the global suspense it make sense to have a global flag passed to LensProvider.

for the individual hooks like usePublications it should probably be duplicated hooks like useSuspensePublications to return the correct types without the loading, error etc props that will not be used as the hook should just return the data.

**Comment by cesarenaldi** [comment]
First PR on this topic: https://github.com/lens-protocol/lens-sdk/pull/902

**Comment by cesarenaldi** [comment]
This is being rolled out to the most common read hooks and will be extended to the few remaining one on a need base.
