### ISSUE TITLE
export 'isObject' (imported as 'isObject') was not found in '@lens-protocol/shared-kernel'

### ISSUE THREAD

**Issue by wmjchf** [lens-protocol/lens-sdk#852]
export 'isObject' (imported as 'isObject') was not found in '@lens-protocol/shared-kernel'

pacakge version:

"@lens-protocol/react-web": "2.0.0-alpha.32",
"@lens-protocol/wagmi": "4.0.0-alpha.1",
"viem": "^2.7.9",
 "wagmi": "^2.5.7"
"@tanstack/react-query": "^5.20.5",

**Comment by cesarenaldi** [comment]
Looks like a dependency was note updated. Checking.

**Comment by cesarenaldi** [comment]
It was a missing dependency. Fix coming soon: https://github.com/lens-protocol/lens-sdk/pull/855

**Comment by cesarenaldi** [comment]
A fix is now available in the `latest` tag of relevant packages. Namely these have been updated to:

- `@lens-protocol/react-native@0.1.0-alpha.10`
- `@lens-protocol/react-web@2.0.0-alpha.33`
- `@lens-protocol/wagmi@4.0.0-alpha.2`

Update the ones relevant for your integration.
