### ISSUE TITLE
verifyFrameSignature: SIGNER_ADDRESS_CANNOT_USE_PROFILE(Lens Frame)

### ISSUE THREAD

**Issue by dudu0506** [lens-protocol/lens-sdk#952]
**Describe the bug**
When I click button, and then I got this response [SIGNER_ADDRESS_CANNOT_USE_PROFILE] when calling lensClient.frames.verifyFrameSignature. And I want to know why I got this? And how to fix it? (Hope to receive more explanation about SignER-ADDRES-CANNOT-USE-PROILE). Thanks very much!

**To Reproduce**
Provide with as much details as possible the call, the hook, the interaction with the Lens SDK that has been problematic for you. Links to public GH repos or working examples are really appreciated.

**Expected behaviuor**

**If using the React bindings, what is the essence of your React app?**
- [ ] React Web App
- [ ] React Native 

**Version of the packages you are using**
Please provide the version of the packages.

**Additional context**

**Comment by cesarenaldi** [comment]
hey @dudu0506,

Can you please clarify the circumstances of how you get this error? What button?

If you fill the rest of the PR template, it will help us reproduce the issue.
