### ISSUE TITLE
Add support for `TRANSACTION` publication format for more chains

### ISSUE THREAD

**Issue by dave4506** [lens-protocol/lens-sdk#965]
**Is your feature request related to a problem? Please describe.**
Currently TRANSACTION format on the lens backend validates against a very limited set of chains, we'd like this to be relaxed or all together removed to allow for any chain to be added as a `TRANSACTION` post.

**Describe the solution you'd like**
Relaxing the validation there.

**Describe alternatives you've considered**
None Applicable

**Additional context**
You can use my handle @dave4506 to see the error on hey.

**Comment by joshstevens19** [comment]
this has been fixed in the API
