### ISSUE TITLE
Remove upper limit of node engine version for client package

### ISSUE THREAD

**Issue by normanzb** [lens-protocol/lens-sdk#966]
Hi my avara fems,

Any idea why do we have the upper limit `< 21` node engine version set for the client package? see code below

https://github.com/lens-protocol/lens-sdk/blob/6f5688811f4532de3cc0c745eead266901f452ef/packages/client/package.json#L100

can we remove that? the latest LTS node version is 22 now.

**Comment by cesarenaldi** [comment]
Hey @normanzb !!

The only reason is that when this was launched first 22 was not stable yet. Rationale for upper limit was just to ensure we can provide support in a controlled fashion.

We are building the new SDK for Lens v3, definitely there we can up this restriction.

**Comment by normanzb** [comment]
hi @cesarenaldi 🤝 you alright mate?

It sounds there is no particular reason to block the new lts. will it take a while for the new v3 sdk to roll out? 
if it takes a while, happy for me to up it now? it is blocking project ci services that uses lens for using latest lts.

PR is here: https://github.com/lens-protocol/lens-sdk/pull/967

**Comment by cesarenaldi** [comment]
Aiming to have feature parity in the SDK by end of the year.

**Comment by normanzb** [comment]
issue closed as PR merged

**Comment by cesarenaldi** [comment]
Published:
🦋  @lens-protocol/cli@0.1.1
🦋  @lens-protocol/client@2.3.2
🦋  @lens-protocol/react@2.3.2
🦋  @lens-protocol/react-native@2.3.2
🦋  @lens-protocol/react-web@2.3.2
🦋  @lens-protocol/wagmi@4.1.5

**Comment by cesarenaldi** [comment]
cc @normanzb

**Comment by normanzb** [comment]
many thanks @cesarenaldi !
